configured_endpoints: 27
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/corespeed-inc-dash%2Fmcp-store-sdk-ba253fbf08a732fb0ca81d456ca38842516182916a67a6ff28bafa597dbe07bf.yml
openapi_spec_hash: 2ae58db716c41ddad2fc303d9fa1defb
config_hash: ec730ea84d48baee6e13e5149151c8ba
