#!/usr/bin/env bash

set -exuo pipefail

cd "$(dirname "$0")/.."

rm -rf dist-deno; mkdir dist-deno
cp -rp src/* jsr.json dist-deno

for file in README.md LICENSE CHANGELOG.md; do
  if [ -e "${file}" ]; then cp "${file}" dist-deno; fi
done

# Patch types.ts to remove node_modules imports that break deno check
node scripts/utils/patch-deno-types.cjs

node scripts/utils/convert-jsr-readme.cjs ./dist-deno/README.md
